// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8UNQW7c4PfL7M010OloxAipuBwpo4q8',
    appId: '1:703869924002:web:347ad78f202dd9dca3ddfb',
    messagingSenderId: '703869924002',
    projectId: 'workout-app-4f002',
    authDomain: 'workout-app-4f002.firebaseapp.com',
    storageBucket: 'workout-app-4f002.firebasestorage.app',
    measurementId: 'G-EBC5PJ0SN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYju2R60UmFtIDNV9dfnOtwZQfHhvHW00',
    appId: '1:703869924002:android:899ea1ea71db7485a3ddfb',
    messagingSenderId: '703869924002',
    projectId: 'workout-app-4f002',
    storageBucket: 'workout-app-4f002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRsP2WuGcEQqaZihLeGYs2t_cWfqWT6Zw',
    appId: '1:703869924002:ios:0cf4566edd3f1684a3ddfb',
    messagingSenderId: '703869924002',
    projectId: 'workout-app-4f002',
    storageBucket: 'workout-app-4f002.firebasestorage.app',
    iosBundleId: 'com.example.workoutAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRsP2WuGcEQqaZihLeGYs2t_cWfqWT6Zw',
    appId: '1:703869924002:ios:0cf4566edd3f1684a3ddfb',
    messagingSenderId: '703869924002',
    projectId: 'workout-app-4f002',
    storageBucket: 'workout-app-4f002.firebasestorage.app',
    iosBundleId: 'com.example.workoutAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_8UNQW7c4PfL7M010OloxAipuBwpo4q8',
    appId: '1:703869924002:web:92c9a419d27dae9ca3ddfb',
    messagingSenderId: '703869924002',
    projectId: 'workout-app-4f002',
    authDomain: 'workout-app-4f002.firebaseapp.com',
    storageBucket: 'workout-app-4f002.firebasestorage.app',
    measurementId: 'G-JH9EH71VXL',
  );
}
